name: ahad_pagi_app
description: Aplikasi Islamic untuk ibadah harian
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  adhan: ^2.0.0
  hijri: ^3.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/asset/logo_splash.png"

flutter:
  uses-material-design: true
  assets:
    - lib/asset/logo_splash.png
